api/urls.py
# from .views import api_news, api_news_detail
from api.views import APIComments, APINews, APINewsDetail, APICommentsDetail, APITag
from django.urls import path

app_name = 'api'
urlpatterns = [
    path('v1/news', APINews.as_view(), name='news'),
    path('v1/news/<int:pk>', APINewsDetail.as_view(), name='news_detail'),
    path('v1/comments/<int:pk>', APIComments.as_view(), name='news_comments'),
    path('v1/comments/<int:pk>',
         APICommentsDetail.as_view(), name='comment_detail'),
    path('v1/news/<int:pk>/tags', APITag.as_view(), name='news_tags'),
]

my_syte/urls.py
from django.contrib.auth.views import LogoutView
"""my_syte URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news_feed/', include('news_feed.urls')),
    path('tags/', include('tags.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
]

news_feed/urls.py
from django.urls import path
from . import views

app_name = 'news_feed'
urlpatterns = [
    # main page
    path('', views.IndexView.as_view(), name='index'),
    # page of details of news
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:news_id>/comment', views.comment, name='comment'),
    path('<int:news_id>/delete/<int:comm_id>',
         views.delete_comment, name='delete'),
    path('register/', views.UserRegister.as_view(), name='register'),
    path('auth/', views.UserLogin.as_view(), name='login'),
]

tags/urls.py
from django.urls import path
from . import views

app_name = 'tags'
urlpatterns = [
    path('', views.IndexViews.as_view(), name='index'),
    path('news/<slug:tag>/', views.TaggedObj.as_view(), name='tagged')
]

news_feed/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from tags.models import TaggedItem
from django.contrib.auth.models import User


class News(models.Model):
    id = models.AutoField(primary_key=True)
    news_title = models.CharField(max_length=200)
    news_previos_text = models.TextField(null=True)
    news_text = models.TextField()
    news_pub_date = models.DateTimeField('Date published', auto_now_add=True)
    news_source_date = models.DateTimeField()
    news_source = models.CharField(max_length=200)
    news_site_id = models.CharField(max_length=100, null=True)
    news_tags = GenericRelation(TaggedItem)

    class Meta:
        ordering = ('-news_source_date',)

    def short_source_name(self):
        if self.news_source.find('http') != -1:
            short_name = self.news_source[:self.news_source.find('/', 8)]
        else:
            short_name = 'None'
        return short_name

    def __str__(self):
        return self.news_title


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    comm_author = models.ForeignKey(User, on_delete=models.CASCADE)
    comm_text = models.TextField()
    pub_date = models.DateTimeField('Date published', auto_now_add=True)
    news = models.ForeignKey(News, on_delete=models.CASCADE,
                             related_name='comments')

    def __str__(self):
        return self.comm_text

news_feed/templates/news_feed/base.html
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'news_feed/favicon.ico' %}"/>

<head><title>{% block head%} News scraper{% endblock%}</title> </head>

<div>
{% block header %} 
    {% if user.is_authenticated %}
        <p align="right">{{user.username}} (<a href="{% url 'logout' %}?next={{request.path}}">LogOut</a>)</p>
    {% else %}
        <p align="right"><a href="{% url 'news_feed:login' %}?next={{request.path}}">Log In</a></p>
    {% endif %}
{% endblock %}
</div>

<div>
{% block content %}

{% endblock %}
</div>

news_feed/templates/news_feed/detail.html
{% extends "news_feed/base.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href=" {% static 'news_feed/style.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'news_feed/favicon.ico' %}"/>
{% block head %}Detail of news{% endblock %}

{%block content%}
    {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
    <h1>{{news.news_title}}</h1>
    <br>
    <p>{{news.news_previos_text}}</p>
    <p> {{news.news_text}} </p>
    <br>
    <b>{{news.news_source}}</b>
    <br>
    <b>{{news.news_pub_date}}</b>
    <br>
    <br>Tags:
    {% for tag in news.news_tags.all %}
        <a href="{% url 'tags:tagged' tag.tag_id %}">{{tag.tag_id}}</a>
    {% endfor %}
    <br>
    <br>
    <a href="{% url 'news_feed:index' %}">Back to main page</a>
    <br>
    <br>
    <h2>All comments:</h2>

    <table>
    {% for comm in news.comments.all%}
        {% if not comm.comm_author.first_name and not comm.comm_author.first_name  %}
            <tr><td> Author:</td> <td>{{comm.comm_author}}</td></tr>
        {% else %}
            <tr><td> Author:</td> <td>{{comm.comm_author.first_name}} {{comm.comm_author.last_name}}</td></tr>
        {% endif %}
        <tr><td>Comment:</td> <td>{{comm.comm_text}}</td></tr>
        {% if comm.comm_author.username == user.username %}
            <tr><td><a href="{% url 'news_feed:delete' news.id comm.id %}">Удалить</a></td></tr>
        {% endif %}
        <tr><td>____</td></tr>
    {% endfor %}
    </table>

    {% if user.is_authenticated %}
        <form action="{% url 'news_feed:comment' news.id %}" method="POST">
            <h2>Add new comment</h2>
            {% csrf_token %}
            <!--<p><input type="text" name="user_name" placeholder="Set you name" ></p> -->
            {% if user.first_name %}
                <p>Вы оставите комментарий как {{ user.first_name }} {{user.last_name}}</p>
            {% else %}
                <p>Вы оставите комментарий как {{ user.username }}</p>
            {% endif %}
            <p><textarea name="comment_text" style="width:25%;" rows=10 placeholder="Set you comment" ></textarea></p>
            <p><input type="submit" value="Add new comment"></p>
        </form>
    {% else %}
        <p>To leave comment, log in</p>
    {% endif %}
{% endblock %}

news_feed/templates/news_feed/index.html
{% extends "news_feed/base.html" %}

{% block content %}
{% if news_list %}
    <table border="1" width="100%" cellpadding="5">
    
        {% for news in news_list %}
            <tr>
            <td><a href="/news_feed/{{news.id}}/?next={{ request.path|urlencode }}" style="font-size:14">{{news.news_title}}</a> </td>
            <td width="20%">{{ news.short_source_name }}</td>
            <td width="20%">{{ news.news_source_date }}</td>
            </tr>
        {% endfor%}
        {% if page_obj.number == page_obj.paginator.num_pages %}
            {% for count in countquery %}
                <tr><td>&nbsp;</td><td width="20%"></td><td width="20%"></td></tr>
            {% endfor%}
        {% endif %}
    </table>    

    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}"> previous </a>
    {% else %}
        &laquo; first previous
    {% endif %}

    {% if page_obj.number|add:'-9' > 1%}
        <a href='?page={{page_obj.number|add:"-9"}}'>&hellip;</a>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}
            {% if page == page_obj.number %}
                <b><a href="?page={{ page }}" > {{ page }}</a></b>
            {% elif page > page_obj.number|add:'-10' and page < page_obj.number|add:'10' %}
                <a href="?page={{ page }}" > {{ page }}</a>
            {% endif %}
    {% endfor %}

    {% if page_obj.number|add:'9' < page_obj.paginator.num_pages %}
        <a href='?page={{page_obj.number|add:"9"}}'>&hellip;</a>
    {% endif %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last ({{ page_obj.paginator.num_pages }}) &raquo;</a>
    {% else%}
        next last({{ page_obj.paginator.num_pages }}) &raquo;
    {% endif %}

{% else %}
    <p>No news now</p>
{%endif%}
{% endblock %}

news_feed/templates/news_feed/login.html
{% if user.is_authenticated %}
    <p>You arr already log in as {{ user.username}}</p>
{% else %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'news_feed:register' %}">Registration</a>
{% endif %}

news_feed/templates/news_feed/register.html
{% if user.is_authenticated %}
    <p>You arr already log in as {{ user.username}}</p>
{% else %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Login">
    </form>

{% endif %}

news_feed/templates/news_feed/registration.html
<form method="POST" class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>